baseURL = "http://kubernetes.egitim.io"
DefaultContentLanguage = "tr"
title = "Kubernetes Eğitimi"
theme = "beautifulhugo"
metaDataFormat = "yaml"
googleAnalytics = "UA-34425776-2"

[Params]
  subtitle = "(Çeviri devam etmektedir)"
  logo = "img/kbe-logo.png"
  favicon = "img/kbe-logo.ico"
  dateFormat = "2006-01-02"
  commit = false
  rss = false

[[menu.main]]
  name = "Kendin dene!"
  url = "diy/"

[[menu.main]]
  name = "Katkıda bulun!"
  url = "https://github.com/ykocaman/kubernetes.egitim.io"
